### ISSUE TITLE
Please resolve the issue getting this after hit this- python -m mn_penpusher --path

### ISSUE THREAD

**Issue by vaibhavsharma3070** [ModernNFTSpace/MultipleNFTUploader#1]
C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe: No module named mn_penpusher.__main__; 'mn_penpusher' is a package and cannot be directly executed

**Comment by s0d3s** [comment]
This is not a MNU error. Please re-clone the repository, or run `git submodule update --init` in the MNU folder.
